// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsqejhyawxhcoqozzdtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzcWVqaHlhd3hoY29xb3p6ZHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Njk1MDYsImV4cCI6MjA1ODE0NTUwNn0.2l18pk1MkBj3E9PGNGqEAey-cl7dHXcUrlgdORXeYj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);